name: lucidmind_frontend
description: A mood-tracking web application for LucidMind.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  over_react: ^5.4.4
  build_runner: ^2.4.6

dev_dependencies:
  build_web_compilers: ^4.0.1
