# Stage 1: Cache Gradle dependencies
FROM gradle:8-jdk17 AS cache
RUN mkdir -p /home/gradle/cache_home
ENV GRADLE_USER_HOME=/home/gradle/cache_home
COPY build.gradle.* gradle.properties settings.gradle* /home/gradle/app/
COPY gradle /home/gradle/app/gradle
WORKDIR /home/gradle/app
RUN gradle build --no-daemon -x test -x compileKotlin -x compileJava || return 0

# Stage 2: Build Application
FROM gradle:8-jdk17 AS build
COPY --from=cache /home/gradle/cache_home /home/gradle/.gradle
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle installDist --no-daemon

# Stage 3: Create the Runtime Image
FROM amazoncorretto:17 AS runtime
EXPOSE 8040
RUN mkdir /app

# Explicitly reference the real directory name (case-sensitive!)
COPY --from=build /home/gradle/src/build/install/LucidMind-Backend/bin /app/bin
COPY --from=build /home/gradle/src/build/install/LucidMind-Backend/lib /app/lib

COPY --from=build /home/gradle/src/src/main/resources/firebase-key.json /app/firebase-key.json

RUN chmod +x /app/bin/*

WORKDIR /app

# Match the actual filename (case-sensitive!)
ENTRYPOINT ["./bin/LucidMind-Backend"]
